### ISSUE TITLE
Command auto complete crash

### ISSUE THREAD

**Issue by Txuritan** [Txuritan/devotion-irc#1]
Steps
  * Join server
  * Press '/'
  * Press 'tab'

Class
  * net.blay09.mods.eirairc.util.Utils.isOP

Code
```java
public static boolean isOP(ICommandSender sender) {
    return FMLCommonHandler.instance().getMinecraftServerInstance().getServer() == null
            || (FMLCommonHandler.instance().getMinecraftServerInstance().getServer().isSinglePlayer()
            && !FMLCommonHandler.instance().getMinecraftServerInstance().getServer().isDedicatedServer())
            || sender.canUseCommand(3, "");
}
```
Crash
```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 5/1/17 9:16 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.blay09.mods.eirairc.util.Utils.isOP(Utils.java:97)
	at net.blay09.mods.eirairc.command.CommandDisconnect.canCommandSenderUseCommand(CommandDisconnect.java:67)
	at net.blay09.mods.eirairc.command.SubCommandWrapper.checkPermission(SubCommandWrapper.java:49)
	at net.minecraft.command.CommandHandler.getTabCompletions(CommandHandler.java:197)
	at net.minecraftforge.client.ClientCommandHandler.autoComplete(ClientCommandHandler.java:144)
	at net.minecraft.util.TabCompleter.requestCompletions(TabCompleter.java:70)
	at net.minecraft.util.TabCompleter.complete(TabCompleter.java:52)
	at net.minecraft.client.gui.GuiChat$ChatTabCompleter.complete(GuiChat.java:279)
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:89)
	at net.blay09.mods.eirairc.client.gui.chat.GuiChatExtended.keyTyped(GuiChatExtended.java:60)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:651)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:599)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1800)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1127)
	at net.minecraft.client.Minecraft.run(Minecraft.java:407)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.blay09.mods.eirairc.util.Utils.isOP(Utils.java:97)
	at net.blay09.mods.eirairc.command.CommandDisconnect.canCommandSenderUseCommand(CommandDisconnect.java:67)
	at net.blay09.mods.eirairc.command.SubCommandWrapper.checkPermission(SubCommandWrapper.java:49)
	at net.minecraft.command.CommandHandler.getTabCompletions(CommandHandler.java:197)
	at net.minecraftforge.client.ClientCommandHandler.autoComplete(ClientCommandHandler.java:144)
	at net.minecraft.util.TabCompleter.requestCompletions(TabCompleter.java:70)
	at net.minecraft.util.TabCompleter.complete(TabCompleter.java:52)
	at net.minecraft.client.gui.GuiChat$ChatTabCompleter.complete(GuiChat.java:279)
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:89)
	at net.blay09.mods.eirairc.client.gui.chat.GuiChatExtended.keyTyped(GuiChatExtended.java:60)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:651)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:599)

-- Affected screen --
Details:
	Screen name: net.blay09.mods.eirairc.client.gui.chat.GuiChatExtended

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player694'/418, l='MpServer', x=0.00, y=54.50, z=0.00]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,61,0), Chunk: (at 0,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 430465 game time, 22436 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 152 total; [EntityPlayerSP['Player694'/418, l='MpServer', x=0.00, y=54.50, z=0.00], EntityItem['item.item.dyePowder.black'/512, l='MpServer', x=159.82, y=22.00, z=115.06], EntityItem['item.item.dyePowder.black'/513, l='MpServer', x=55.74, y=11.00, z=-142.43], EntityItem['item.tile.rail'/514, l='MpServer', x=-159.53, y=24.00, z=-18.16], EntityItem['item.item.string'/515, l='MpServer', x=-169.97, y=24.00, z=11.02], EntityItem['item.tile.rail'/516, l='MpServer', x=-167.88, y=21.00, z=-0.23], EntityItem['item.tile.rail'/517, l='MpServer', x=-167.54, y=20.00, z=13.40], EntityItem['item.tile.rail'/518, l='MpServer', x=-170.21, y=19.00, z=20.28], EntityItem['item.tile.rail'/519, l='MpServer', x=-174.88, y=24.00, z=26.45], EntityPig['Pig'/521, l='MpServer', x=-155.70, y=64.00, z=108.49], EntityHorse['Horse'/522, l='MpServer', x=-157.51, y=64.00, z=115.57], EntityBat['Bat'/523, l='MpServer', x=-156.91, y=25.00, z=133.47], EntityPig['Pig'/524, l='MpServer', x=-163.02, y=64.00, z=121.07], EntityPig['Pig'/525, l='MpServer', x=-171.94, y=65.00, z=109.47], EntityChicken['Chicken'/526, l='MpServer', x=-119.07, y=67.34, z=172.81], EntityChicken['Chicken'/527, l='MpServer', x=-116.70, y=64.00, z=161.76], EntitySquid['Squid'/529, l='MpServer', x=-160.50, y=60.00, z=-30.91], EntitySquid['Squid'/530, l='MpServer', x=-160.50, y=60.00, z=-33.22], EntityItem['item.tile.rail'/531, l='MpServer', x=-160.88, y=24.00, z=-20.75], EntityItem['item.tile.rail'/532, l='MpServer', x=-174.04, y=30.00, z=-9.95], EntitySpider['Spider'/533, l='MpServer', x=-98.97, y=77.69, z=134.50], EntitySpider['Spider'/534, l='MpServer', x=-84.09, y=81.00, z=145.16], EntitySpider['Spider'/535, l='MpServer', x=-88.57, y=82.00, z=143.38], EntitySpider['Spider'/536, l='MpServer', x=-20.74, y=75.00, z=95.39], EntitySpider['Spider'/537, l='MpServer', x=-18.88, y=77.00, z=104.69], EntitySpider['Spider'/538, l='MpServer', x=-15.50, y=76.69, z=102.56], EntityBat['Bat'/539, l='MpServer', x=100.03, y=25.88, z=22.97], EntityBat['Bat'/540, l='MpServer', x=-172.35, y=30.00, z=106.53], EntitySheep['Sheep'/541, l='MpServer', x=-189.55, y=67.00, z=120.39], EntityBat['Bat'/542, l='MpServer', x=-185.94, y=34.00, z=-101.55], EntityItem['item.tile.rail'/546, l='MpServer', x=-177.76, y=31.00, z=-15.06], EntityItem['item.tile.torch'/547, l='MpServer', x=-181.01, y=30.00, z=-10.16], EntityItem['item.item.string'/548, l='MpServer', x=-178.96, y=30.00, z=-10.81], EntityItem['item.item.string'/549, l='MpServer', x=-184.86, y=31.00, z=-8.03], EntityItem['item.item.string'/550, l='MpServer', x=-184.05, y=31.00, z=-2.86], EntityItem['item.tile.rail'/551, l='MpServer', x=-184.42, y=31.00, z=-10.18], EntityItem['item.tile.rail'/552, l='MpServer', x=-180.95, y=30.00, z=-10.18], EntityItem['item.tile.rail'/553, l='MpServer', x=-179.11, y=30.00, z=-10.11], EntityItem['item.tile.rail'/554, l='MpServer', x=-184.32, y=31.00, z=-4.95], EntityItem['item.tile.rail'/555, l='MpServer', x=-175.78, y=30.00, z=-9.13], EntityItem['item.tile.rail'/556, l='MpServer', x=-181.67, y=31.00, z=-15.02], EntityItem['item.tile.rail'/557, l='MpServer', x=-183.15, y=19.00, z=13.40], EntityItem['item.tile.rail'/558, l='MpServer', x=-182.04, y=19.00, z=12.66], EntityItem['item.tile.rail'/560, l='MpServer', x=-182.94, y=19.00, z=20.32], EntityItem['item.tile.rail'/561, l='MpServer', x=-182.31, y=19.00, z=22.24], EntityItem['item.tile.rail'/562, l='MpServer', x=-182.38, y=19.00, z=25.80], EntityItem['item.tile.rail'/563, l='MpServer', x=-183.88, y=19.00, z=28.46], EntityBat['Bat'/564, l='MpServer', x=-61.50, y=19.73, z=68.50], EntityBat['Bat'/565, l='MpServer', x=-154.70, y=21.00, z=-190.89], EntityHorse['Horse'/566, l='MpServer', x=-134.13, y=65.00, z=197.63], EntityHorse['Horse'/567, l='MpServer', x=-132.97, y=68.00, z=200.59], EntityHorse['Horse'/568, l='MpServer', x=-132.38, y=65.00, z=195.31], EntityHorse['Horse'/569, l='MpServer', x=-135.09, y=64.00, z=193.47], EntityBat['Bat'/570, l='MpServer', x=128.29, y=18.00, z=-185.58], EntityZombie['Zombie'/571, l='MpServer', x=-68.81, y=64.00, z=-10.06], EntityBat['Bat'/572, l='MpServer', x=86.38, y=24.64, z=33.31], EntityCreeper['Creeper'/584, l='MpServer', x=36.50, y=64.00, z=93.50], EntityCreeper['Creeper'/585, l='MpServer', x=24.50, y=64.00, z=111.50], EntityBat['Bat'/586, l='MpServer', x=-106.50, y=19.00, z=19.50], EntityBat['Bat'/587, l='MpServer', x=-111.50, y=19.00, z=31.50], EntityBat['Bat'/588, l='MpServer', x=22.50, y=30.00, z=123.50], EntityBat['Bat'/419, l='MpServer', x=37.94, y=21.00, z=39.31], EntityCow['Cow'/420, l='MpServer', x=15.27, y=70.00, z=81.20], EntityPig['Pig'/421, l='MpServer', x=20.19, y=68.00, z=77.29], EntityPig['Pig'/422, l='MpServer', x=33.54, y=67.00, z=76.63], EntityBat['Bat'/423, l='MpServer', x=53.37, y=31.00, z=81.10], EntityBat['Bat'/424, l='MpServer', x=52.64, y=31.97, z=79.90], EntityBat['Bat'/425, l='MpServer', x=52.10, y=30.00, z=80.00], EntityCow['Cow'/426, l='MpServer', x=29.77, y=67.00, z=93.36], EntityPig['Pig'/427, l='MpServer', x=29.50, y=65.00, z=108.13], EntityBat['Bat'/428, l='MpServer', x=-2.62, y=52.85, z=102.09], EntityBat['Bat'/429, l='MpServer', x=-12.35, y=53.00, z=109.87], EntityBat['Bat'/430, l='MpServer', x=-13.94, y=52.97, z=100.01], EntityBat['Bat'/431, l='MpServer', x=-16.79, y=33.22, z=107.50], EntityPig['Pig'/432, l='MpServer', x=-41.19, y=59.91, z=109.97], EntityPig['Pig'/433, l='MpServer', x=14.49, y=65.00, z=119.63], EntitySquid['Squid'/434, l='MpServer', x=75.50, y=45.00, z=114.50], EntitySquid['Squid'/435, l='MpServer', x=75.50, y=52.00, z=99.50], EntityChicken['Chicken'/436, l='MpServer', x=-74.55, y=66.00, z=29.07], EntityGuardian['Guardian'/437, l='MpServer', x=-75.50, y=39.00, z=-72.50], EntityGuardian['Guardian'/438, l='MpServer', x=-69.50, y=38.00, z=-68.50], EntitySquid['Squid'/439, l='MpServer', x=95.72, y=33.00, z=9.50], EntitySquid['Squid'/440, l='MpServer', x=93.50, y=34.00, z=18.50], EntitySquid['Squid'/441, l='MpServer', x=102.50, y=46.00, z=0.50], EntityBat['Bat'/442, l='MpServer', x=107.51, y=23.00, z=-94.18], EntityGuardian['Guardian'/443, l='MpServer', x=-92.50, y=52.00, z=-64.27], EntityItem['item.tile.rail'/444, l='MpServer', x=-92.13, y=27.00, z=1.88], EntityChicken['Chicken'/445, l='MpServer', x=-84.87, y=65.00, z=27.20], EntityChicken['Chicken'/446, l='MpServer', x=-83.12, y=66.00, z=33.81], EntityGuardian['Guardian'/447, l='MpServer', x=-74.50, y=38.00, z=-94.50], EntitySquid['Squid'/448, l='MpServer', x=82.50, y=46.00, z=125.50], EntityZombie['Zombie'/449, l='MpServer', x=-65.40, y=62.00, z=-31.51], EntityItem['item.tile.rail'/451, l='MpServer', x=-99.75, y=26.00, z=11.13], EntityItem['item.tile.rail'/452, l='MpServer', x=-99.75, y=27.00, z=1.57], EntityItem['item.tile.rail'/453, l='MpServer', x=-106.16, y=26.00, z=12.00], EntityItem['item.tile.rail'/454, l='MpServer', x=-110.89, y=26.00, z=12.00], EntityItem['item.tile.rail'/455, l='MpServer', x=-101.44, y=27.00, z=1.88], EntityItem['item.tile.rail'/456, l='MpServer', x=-98.23, y=26.00, z=13.07], EntityBat['Bat'/457, l='MpServer', x=-113.17, y=13.00, z=15.83], EntityChicken['Chicken'/458, l='MpServer', x=-106.57, y=63.00, z=-6.73], EntityItem['item.tile.rail'/459, l='MpServer', x=-103.40, y=26.00, z=23.76], EntityItem['item.tile.rail'/460, l='MpServer', x=-103.22, y=26.00, z=17.70], EntityItem['item.tile.rail'/461, l='MpServer', x=-102.12, y=26.00, z=25.97], EntityItem['item.tile.torch'/462, l='MpServer', x=-102.44, y=26.00, z=21.56], EntityItem['item.tile.rail'/463, l='MpServer', x=-102.51, y=26.00, z=22.00], EntityItem['item.tile.rail'/464, l='MpServer', x=-103.88, y=26.00, z=31.25], EntityItem['item.tile.rail'/465, l='MpServer', x=-101.69, y=26.00, z=32.97], EntitySheep['Sheep'/466, l='MpServer', x=-101.96, y=63.00, z=108.01], EntityBat['Bat'/467, l='MpServer', x=-104.29, y=47.22, z=120.62], EntitySheep['Sheep'/468, l='MpServer', x=-100.95, y=64.00, z=115.76], EntitySquid['Squid'/469, l='MpServer', x=107.50, y=41.00, z=114.39], EntitySquid['Squid'/470, l='MpServer', x=107.50, y=41.00, z=112.11], EntitySquid['Squid'/471, l='MpServer', x=103.50, y=40.00, z=124.50], EntitySquid['Squid'/472, l='MpServer', x=-112.50, y=49.00, z=-30.50], EntitySquid['Squid'/473, l='MpServer', x=-112.50, y=49.00, z=-30.50], EntitySquid['Squid'/474, l='MpServer', x=131.50, y=37.00, z=-13.50], EntityItem['item.tile.rail'/475, l='MpServer', x=-114.88, y=26.00, z=11.13], EntityItem['item.tile.rail'/476, l='MpServer', x=-118.92, y=26.00, z=12.64], EntityChicken['Chicken'/477, l='MpServer', x=-114.24, y=64.00, z=10.76], EntityPig['Pig'/478, l='MpServer', x=-125.33, y=64.00, z=12.35], EntityBat['Bat'/479, l='MpServer', x=-127.87, y=19.00, z=49.50], EntitySquid['Squid'/480, l='MpServer', x=128.50, y=43.00, z=51.50], EntitySquid['Squid'/481, l='MpServer', x=128.50, y=43.00, z=51.50], EntityBat['Bat'/482, l='MpServer', x=-117.10, y=25.94, z=102.10], EntityBat['Bat'/483, l='MpServer', x=-119.45, y=22.59, z=96.10], EntityBat['Bat'/484, l='MpServer', x=-121.72, y=26.90, z=110.47], EntityItem['item.tile.rail'/485, l='MpServer', x=-136.77, y=28.00, z=-36.55], EntityItem['item.tile.rail'/486, l='MpServer', x=-137.88, y=28.00, z=-33.25], EntityItem['item.tile.torch'/487, l='MpServer', x=-141.06, y=29.00, z=-30.00], EntityItem['item.item.string'/488, l='MpServer', x=-137.11, y=28.00, z=-23.71], EntityItem['item.tile.torch'/489, l='MpServer', x=-136.36, y=28.00, z=-23.00], EntityItem['item.tile.rail'/490, l='MpServer', x=-140.35, y=29.00, z=-30.23], EntityItem['item.tile.rail'/491, l='MpServer', x=-135.95, y=28.00, z=-26.71], EntityItem['item.tile.rail'/492, l='MpServer', x=-141.99, y=29.00, z=-25.79], EntityItem['item.tile.rail'/493, l='MpServer', x=-141.43, y=29.00, z=-25.03], EntityItem['item.tile.rail'/494, l='MpServer', x=-136.87, y=28.00, z=-23.03], EntityItem['item.tile.rail'/495, l='MpServer', x=-141.97, y=29.00, z=-22.11], EntityItem['item.tile.rail'/496, l='MpServer', x=-137.79, y=28.00, z=-19.99], EntityItem['item.tile.rail'/497, l='MpServer', x=-136.47, y=28.00, z=-28.00], EntityItem['item.tile.rail'/498, l='MpServer', x=-142.31, y=29.00, z=-18.96], EntityItem['item.tile.rail'/499, l='MpServer', x=-135.38, y=28.00, z=-18.75], EntityItem['item.tile.rail'/500, l='MpServer', x=-137.88, y=28.00, z=-16.13], EntityItem['item.tile.rail'/501, l='MpServer', x=-136.23, y=18.00, z=-17.83], EntityHorse['Horse'/503, l='MpServer', x=-148.07, y=63.00, z=13.34], EntityHorse['Horse'/504, l='MpServer', x=-146.12, y=64.00, z=14.49], EntityHorse['Horse'/505, l='MpServer', x=-157.66, y=64.00, z=10.54], EntityHorse['Horse'/506, l='MpServer', x=-154.46, y=64.00, z=3.43], EntityPig['Pig'/507, l='MpServer', x=-132.10, y=63.00, z=28.54], EntityPig['Pig'/508, l='MpServer', x=-140.12, y=64.00, z=38.62], EntityHorse['Horse'/509, l='MpServer', x=-134.54, y=64.00, z=103.50], EntityHorse['Horse'/510, l='MpServer', x=-135.44, y=64.00, z=94.11], EntityHorse['Horse'/511, l='MpServer', x=-134.53, y=64.00, z=100.36]]
	Retry entities: 0 total; []
	Server brand: Cuberite
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:451)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2782)
	at net.minecraft.client.Minecraft.run(Minecraft.java:428)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121-1-ojdkbuild, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 374198688 bytes (356 MB) / 1047527424 bytes (999 MB) up to 1890582528 bytes (1803 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.11.2-13.20.0.2228.jar) 
	UCHIJA	forge{13.20.0.2228} [Minecraft Forge] (forgeSrc-1.11.2-13.20.0.2228.jar) 
	UCHIJA	eirairc{${version}} [EiraIRC] (EiraIRC_main) 
	UCHIJA	eiramoticons{5.2.1} [EiraMoticons] (EiraMoticons_1.11-5.2.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: 1.11.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4549, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
```

**Comment by Txuritan** [comment]
As of now this does stop it, it probably returns false all the time though.

```java
public static boolean isOP(ICommandSender sender) {
    try {
        return sender.getEntityWorld().getMinecraftServer().getServer() != null && (sender.getEntityWorld().getMinecraftServer().getServer() == null || (sender.getEntityWorld().getMinecraftServer().getServer().isSinglePlayer() && !sender.getEntityWorld().getMinecraftServer().getServer().isDedicatedServer()) || sender.canUseCommand(3, ""));
    } catch (NullPointerException npe) {
        npe.getStackTrace();
        return false;
    }
}
```
