### ISSUE TITLE
MC1.11.2 EiraIRC 2 mc1.11.2-5.0.1 doesn't like loading on a server

### ISSUE THREAD

**Issue by sandalle** [Txuritan/devotion-irc#2]
Eira IRC 2 doesn't seem to like loading on a server after I configure a simple configs/eirairc/servers.json from the example provided. While it does join the IRC channel, nothing I type in the channel shows up in-game and nothing in-game shows up in IRC. The session eventually disconnects itself from IRC with no reason given in IRC (not even a notice that it disconnected).

Mods:
* Forge Mod Loader 1.11.2-13.20.0.2294
* Eira IRC 2 mc1.11.2-5.0.1

`[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.blay09.mods.eirairc.util.Utils.addMessageToChat(Utils.java:59)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:89)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:81)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.blay09.mods.eirairc.util.ChatComponentBuilder.send(ChatComponentBuilder.java:57)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.blay09.mods.eirairc.util.ChatComponentBuilder.send(ChatComponentBuilder.java:46)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.blay09.mods.eirairc.handler.IRCEventHandler.fireConnectionFailedEvent(IRCEventHandler.java:381)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:223)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at java.lang.Thread.run(Thread.java:745)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       ... 8 more
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3b77a04f from coremod FMLCorePlugin
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:257)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       ... 10 more
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: Attempted to load class bes for invalid side SERVER
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
[10:35:47] [IRC (irc.synirc.net)/INFO]: [STDERR]:       ... 12 more`

**Comment by Kzitold** [comment]
Does it give a notice it connected in the first place?

**Comment by sandalle** [comment]
I don't recall if my server logged the connection (I've since purged the logs), but I did see the client in the IRC channel before it disconnected.

**Comment by Txuritan** [comment]
The problem was unknowingly caused when I had to update the addMessageToChat method. It references the EntityPlayerSP class and the sendMessage method which uses the ingameGUI variable. The EntityPlayerSP class and sendMessage method are both client only. I should have this fixed in the next release.

**Comment by Txuritan** [comment]
This has been fixed, as far as I know (from the testing I've done), in 5.0.2.

**Comment by sandalle** [comment]
With 5.0.2 I'm able to join IRC from the server, thanks. :)
