### ISSUE TITLE
incoming twitch chat messages not showing up in client mode

### ISSUE THREAD

**Issue by erisdev** [Txuritan/devotion-irc#6]
* multimc 0.6.1-1118
* minecraft 1.12.2
* eirairc-mc1.12.2-5.0.5

```
[16:01:02] [main/ERROR] [net.blay09.mods.eirairc.EiraIRC/]: Utils.addMessageToChat()
java.lang.NullPointerException: null
  at net.blay09.mods.eirairc.util.Utils.addMessageToChat(Utils.java:51) [Utils.class:?]
  at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:90) [EiraIRC$1.class:?]
  at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:82) [EiraIRC$1.class:?]
  at net.blay09.mods.eirairc.handler.MCEventHandler.onClientChat(MCEventHandler.java:161) [MCEventHandler.class:?]
  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_298_MCEventHandler_onClientChat_ClientChatEvent.invoke(.dynamic) [?:?]
  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
  at net.blay09.mods.eirairc.client.gui.chat.GuiChatExtension.keyTyped(GuiChatExtension.java:197) [GuiChatExtension.class:?]
  at net.blay09.mods.eirairc.client.gui.chat.GuiChatExtended.func_73869_a(GuiChatExtended.java:59) [GuiChatExtended.class:?]
  at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558) [blk.class:?]
  at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) [blk.class:?]
  at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757) [bib.class:?]
  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) [bib.class:?]
  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
  at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
  at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
  at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
  at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by erisdev** [comment]
friend says rolling back to 5.0.3 fixes the issue

**Comment by Txuritan** [comment]
Is it sad that I don't know what half of EiraIRC's modes do...

Anywho this should have been fixed with 5.0.5 but I guess not. The only way I can think of this breaking (again) is that you are somehow connected to a server that doesn't exsist, at least to the client.
